from django.contrib import admin
from .models import *

admin.site.register(ArticleProcessPDF)
admin.site.register(Client)
admin.site.register(Color)
admin.site.register(Container)
admin.site.register(ContainerSelectedTrajectory)
admin.site.register(Fabric)
admin.site.register(FabricBatch)
admin.site.register(FabricFamily)
admin.site.register(FabricProcess)
admin.site.register(FabricRoll)
admin.site.register(FabricType)
admin.site.register(Item)
admin.site.register(Order)
admin.site.register(ParameterFabricProcess)
admin.site.register(ParameterStart)
admin.site.register(Priority)
admin.site.register(Process)
admin.site.register(ProcessMachinery)
admin.site.register(QualityField)
admin.site.register(QualityType)
admin.site.register(QualityValues)
admin.site.register(Reason)
admin.site.register(Route)
admin.site.register(RoutePoint)
admin.site.register(SelectedPath)
admin.site.register(Stop)
