# Generated by Django 5.0.1 on 2024-02-01 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMachinery',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('auxiliary_roll_number', models.IntegerField(blank=True, db_column='numero_rol_auxiliar', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'maquinaria_base',
            },
        ),
        migrations.CreateModel(
            name='BehavioralField',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('type_behavioral_field', models.IntegerField(choices=[(1, 'Características Individuales'), (2, 'Mejora Continua')], db_column='tipo')),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='estado', default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'campo_conductual',
            },
        ),
        migrations.CreateModel(
            name='MachineryGroup',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_column='fecha_inicio')),
                ('end_date', models.DateField(db_column='fecha_fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'grupo_maquinaria',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('start_time', models.TimeField(db_column='hora_inicio')),
                ('end_time', models.TimeField(db_column='hora_fin')),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='estado', default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'turno',
            },
        ),
        migrations.CreateModel(
            name='TechnicalField',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='estado', default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'campo_tecnico',
            },
        ),
        migrations.CreateModel(
            name='BehavioralEvaluation',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('puntuaje', models.IntegerField(db_column='puntuaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('empleado_code', models.ForeignKey(db_column='empleado_codigo', on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
                ('campo_conductual_code', models.ForeignKey(db_column='campo_conductual_codigo', on_delete=django.db.models.deletion.CASCADE, to='tareo.behavioralfield')),
            ],
            options={
                'db_table': 'evaluacion_conductual',
            },
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='descripcion', max_length=255)),
                ('image', models.ImageField(blank=True, db_column='imagen', null=True, upload_to='images/machinery/')),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='estado', default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('base_machinery_code', models.ForeignKey(db_column='maquinaria_base_codigo', on_delete=django.db.models.deletion.CASCADE, to='tareo.basemachinery')),
            ],
            options={
                'db_table': 'maquinaria',
            },
        ),
        migrations.CreateModel(
            name='MachineryConfiguration',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('weight', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], db_column='peso')),
                ('shift_quantity', models.IntegerField(db_column='cantidad_turnos')),
                ('percentage_utilization', models.IntegerField(db_column='porcentaje_utilizacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('machinery_code', models.ForeignKey(db_column='maquinaria_codigo', on_delete=django.db.models.deletion.CASCADE, to='tareo.machinery')),
                ('machinery_group_code', models.ForeignKey(db_column='grupo_maquinaria_codigo', on_delete=django.db.models.deletion.CASCADE, to='tareo.machinerygroup')),
            ],
            options={
                'db_table': 'configuracion_maquina',
            },
        ),
        migrations.CreateModel(
            name='OperatorMachineBase',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(1, 'Operario'), (2, 'Auxioliar')], db_column='rol')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('employee_code', models.ForeignKey(db_column='empleado_codigo', on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
                ('machinery_base_code', models.ForeignKey(db_column='maquinaria_base_codigo', on_delete=django.db.models.deletion.CASCADE, to='tareo.basemachinery')),
            ],
            options={
                'db_table': 'operario_maquinaria_base',
                'unique_together': {('machinery_base_code', 'employee_code')},
            },
        ),
        migrations.CreateModel(
            name='TechnicalEvaluation',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('score', models.IntegerField(db_column='puntuaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('operator_machine_base_code', models.ForeignKey(db_column='operario_maquinaria_base_codigo', on_delete=django.db.models.deletion.CASCADE, to='tareo.operatormachinebase')),
                ('technical_fields_code', models.ForeignKey(db_column='campo_tecnico_codigo', on_delete=django.db.models.deletion.CASCADE, to='tareo.technicalfield')),
            ],
            options={
                'db_table': 'evaluacion_tecnica',
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_column='fecha_inicio')),
                ('end_date', models.DateField(db_column='fecha_fin')),
                ('role', models.IntegerField(choices=[(1, 'Operario'), (2, 'Auxioliar')], db_column='rol')),
                ('type_work_log', models.IntegerField(choices=[(1, 'Algoritmo automatico'), (2, 'Modificacion de un usuario')], db_column='tipo')),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='estado', default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('employee_code', models.ForeignKey(db_column='empleado_codigo', on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
                ('machinery_group_code', models.ForeignKey(db_column='grupo_maquinaria_codigo', on_delete=django.db.models.deletion.CASCADE, to='tareo.machinerygroup')),
                ('shift_code', models.ForeignKey(db_column='turno_codigo', on_delete=django.db.models.deletion.CASCADE, to='tareo.shift')),
            ],
            options={
                'db_table': 'tareo',
            },
        ),
    ]
