# Generated by Django 5.0.1 on 2024-02-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='base_machinery_code',
            field=models.ForeignKey(blank=True, db_column='maquinaria_base_codigo', null=True, on_delete=django.db.models.deletion.CASCADE, to='tareo.basemachinery'),
        ),
    ]
