# Generated by Django 5.0.1 on 2024-02-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0002_alter_machinery_base_machinery_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='behavioralevaluation',
            old_name='campo_conductual_code',
            new_name='behavioral_field_code',
        ),
        migrations.RenameField(
            model_name='behavioralevaluation',
            old_name='empleado_code',
            new_name='employee_code',
        ),
        migrations.RemoveField(
            model_name='behavioralevaluation',
            name='puntuaje',
        ),
        migrations.AddField(
            model_name='behavioralevaluation',
            name='score',
            field=models.IntegerField(db_column='puntuaje', default=0),
        ),
        migrations.AddField(
            model_name='behavioralevaluation',
            name='status',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='estado', default='A', max_length=1),
        ),
    ]
