# Generated by Django 5.0.1 on 2024-02-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0003_rename_campo_conductual_code_behavioralevaluation_behavioral_field_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='codigo', max_length=50)),
                ('name', models.CharField(db_column='nombre', max_length=100)),
            ],
            options={
                'db_table': 'parametro',
            },
        ),
        migrations.AlterField(
            model_name='behavioralevaluation',
            name='score',
            field=models.FloatField(db_column='puntuaje', default=0),
        ),
        migrations.AlterField(
            model_name='machineryconfiguration',
            name='percentage_utilization',
            field=models.FloatField(db_column='porcentaje_utilizacion'),
        ),
        migrations.AlterField(
            model_name='technicalevaluation',
            name='score',
            field=models.FloatField(db_column='puntuaje'),
        ),
        migrations.CreateModel(
            name='MachineParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='codigo', max_length=50)),
                ('minimum', models.FloatField(db_column='minimo')),
                ('maximum', models.FloatField(db_column='maximo')),
                ('unit', models.CharField(db_column='unidad', max_length=10)),
                ('machinery', models.ManyToManyField(db_column='maquinaria', related_name='parameters', to='tareo.machinery')),
                ('parameter', models.ForeignKey(db_column='parametro', on_delete=django.db.models.deletion.CASCADE, to='tareo.parameter')),
            ],
            options={
                'db_table': 'parametro_maquina',
            },
        ),
    ]
