# Generated by Django 5.0.1 on 2024-02-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0005_alter_machinerygroup_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='line',
            field=models.CharField(blank=True, choices=[('A', 'Abierta'), ('T', 'Tubular'), ('H', 'Ambas')], db_column='linea', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='basemachinery',
            name='name',
            field=models.CharField(blank=True, db_column='nombre', max_length=255, null=True),
        ),
    ]
