# Generated by Django 5.0.1 on 2024-02-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0006_machinery_line_alter_basemachinery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemachinery',
            name='code',
            field=models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False),
        ),
    ]
