# Generated by Django 5.0.1 on 2024-02-15 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0007_alter_basemachinery_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineparameter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creacion', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machineparameter',
            name='preference',
            field=models.IntegerField(choices=[(0, 'Nula'), (1, 'Muy baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy alta')], db_column='preferencia', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machineparameter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='modificacion'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creacion', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='modificacion'),
        ),
    ]
