# Generated by Django 5.0.1 on 2024-02-01 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleProcessPDF',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('instructions_pdf', models.FileField(blank=True, db_column='pdf_indicaciones', null=True, upload_to='files/article_process_pdf/instructions_pdf/')),
                ('recipe_pdf', models.FileField(blank=True, db_column='pdf_receta', null=True, upload_to='files/article_process_pdf/recipe_pdf/')),
                ('recommendations_pdf', models.FileField(blank=True, db_column='pdf_recomendaciones', null=True, upload_to='files/article_process_pdf/recommendations_pdf/')),
                ('required_instructions', models.BooleanField(blank=True, db_column='obligatorio_indicaciones', null=True)),
                ('required_recipe', models.BooleanField(blank=True, db_column='obligatorio_receta', null=True)),
                ('required_recommendations', models.BooleanField(blank=True, db_column='obligatorio_recomendaciones', null=True)),
                ('read_instructions', models.BooleanField(blank=True, db_column='leido_indicaciones', default=False, null=True)),
                ('read_recipe', models.BooleanField(blank=True, db_column='leido_receta', default=False, null=True)),
                ('read_recommendations', models.BooleanField(blank=True, db_column='leido_recomendaciones', default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'partida_articulo_proceso_pdf',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='correo', max_length=255, null=True)),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('phone', models.IntegerField(blank=True, db_column='telefono', null=True)),
                ('address', models.CharField(blank=True, db_column='direccion', max_length=255, null=True)),
                ('abbreviated_name', models.CharField(blank=True, db_column='nombre_abreviado', max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, db_column='nombre_corto', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('hexadecimal', models.CharField(blank=True, db_column='hexadecimal', max_length=255, null=True)),
                ('rgb', models.CharField(blank=True, db_column='rgb', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, db_column='modelo', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, db_column='imagen/container/', null=True, upload_to='')),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='estado', default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'contenedor',
            },
        ),
        migrations.CreateModel(
            name='FabricFamily',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nombre', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'familia_tejido',
            },
        ),
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nombre', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'tipo_tejido',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('delivery_deadline', models.DateField(db_column='fecha_limite_entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'partida',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'prioridad',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'proceso',
            },
        ),
        migrations.CreateModel(
            name='QualityType',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'tipo_calidad',
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='descripcion', max_length=255)),
                ('type_reason', models.IntegerField(choices=[(1, 'Parada no programada'), (2, 'Parada programada'), (3, 'Llamada supervisor')], db_column='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'razon',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nombre', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'ruta',
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('technical_sheet', models.FileField(blank=True, db_column='ficha_tecnica', null=True, upload_to='files/fabric/technical_sheet/')),
                ('instructions', models.FileField(blank=True, db_column='instrucciones', null=True, upload_to='files/fabric/instructions/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('color_code', models.ForeignKey(db_column='color_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.color')),
                ('fabric_family_code', models.ForeignKey(db_column='familia_tejido_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.fabricfamily')),
                ('fabric_type_code', models.ForeignKey(db_column='tipo_tejido_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.fabrictype')),
                ('route_code', models.ForeignKey(blank=True, db_column='ruta_codigo', null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.route')),
            ],
            options={
                'db_table': 'tela',
            },
        ),
        migrations.CreateModel(
            name='FabricBatch',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('process_quantity', models.IntegerField(db_column='cantidad_procesar')),
                ('unit_of_measure', models.CharField(db_column='unidad_medida', max_length=255)),
                ('target_date', models.DateField(db_column='fecha_objetivo')),
                ('destination_type', models.IntegerField(blank=True, choices=[(1, 'Propio'), (2, 'Tercero')], db_column='tipo_destino', null=True)),
                ('packaging_type', models.IntegerField(blank=True, choices=[(1, 'Rollo'), (2, 'Parihuela'), (3, 'Tacho'), (4, 'Otros')], db_column='tipo_embalaje', null=True)),
                ('production_type', models.IntegerField(blank=True, choices=[(1, 'Producción'), (2, 'Muestras'), (3, 'Desarrollos'), (4, 'Reposición')], db_column='tipo_produccion', null=True)),
                ('observations', models.CharField(blank=True, db_column='observaciones', max_length=255, null=True)),
                ('instructions', models.FileField(blank=True, db_column='instrucciones', null=True, upload_to='files/fabric_batch/instructions/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('fabric_code', models.ForeignKey(db_column='tela_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.fabric')),
                ('batch_code', models.ForeignKey(db_column='partida_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.item')),
                ('priority_code', models.ForeignKey(blank=True, db_column='prioridad_codigo', null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.priority')),
            ],
            options={
                'db_table': 'partida_tela',
                'unique_together': {('batch_code', 'fabric_code')},
            },
        ),
        migrations.CreateModel(
            name='FabricRoll',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('kilograms', models.IntegerField(db_column='kilos')),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='estado', default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('fabric_batch_code', models.ForeignKey(db_column='partida_tela_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.fabricbatch')),
            ],
            options={
                'db_table': 'rollo_tela',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, db_column='fecha_pedido', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('client_code', models.ForeignKey(db_column='cliente_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.client')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='order_code',
            field=models.ForeignKey(db_column='pedido_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.order'),
        ),
        migrations.CreateModel(
            name='FabricProcess',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('fabric_code', models.ForeignKey(db_column='tela_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.fabric')),
                ('process_code', models.ForeignKey(db_column='proceso_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.process')),
            ],
            options={
                'db_table': 'proceso_tela',
            },
        ),
        migrations.CreateModel(
            name='ProcessMachinery',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('speed_kg', models.IntegerField(blank=True, db_column='velocidad_kg', null=True)),
                ('speed_mts', models.IntegerField(blank=True, db_column='velocidad_mts', null=True)),
                ('cost_dollars_kg', models.IntegerField(blank=True, db_column='costo_dolares_kg', null=True)),
                ('cost_dollars_mts', models.IntegerField(blank=True, db_column='costo_dolares_mts', null=True)),
                ('supplies', models.FileField(blank=True, db_column='insumos', null=True, upload_to='files/process_machinery/supplies/')),
                ('specifications', models.FileField(blank=True, db_column='especificaciones', null=True, upload_to='files/process_machinery/specifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('fabric_process_code', models.ForeignKey(db_column='proceso_tela_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.fabricprocess')),
                ('machinery_code', models.ForeignKey(db_column='maquinaria_codigo', on_delete=django.db.models.deletion.CASCADE, to='tareo.machinery')),
            ],
            options={
                'db_table': 'procesomaquinaria',
            },
        ),
        migrations.CreateModel(
            name='QualityField',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('standard_value', models.IntegerField(blank=True, db_column='valor_estandar', null=True)),
                ('min_approval', models.IntegerField(blank=True, db_column='minimo_aprobacion', null=True)),
                ('max_approval', models.IntegerField(blank=True, db_column='maximo_aprobacion', null=True)),
                ('min_alert', models.IntegerField(blank=True, db_column='minimo_alerta', null=True)),
                ('max_alert', models.IntegerField(blank=True, db_column='maximo_alerta', null=True)),
                ('evaluable', models.IntegerField(blank=True, db_column='evaluable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('type_quality_code', models.ForeignKey(db_column='tipo_calidad_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.qualitytype')),
            ],
            options={
                'db_table': 'campo_calidad',
            },
        ),
        migrations.CreateModel(
            name='QualityValues',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('value', models.IntegerField(db_column='valor')),
                ('result', models.IntegerField(blank=True, db_column='resultado', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('quality_field_code', models.ForeignKey(db_column='campo_calidad_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.qualityfield')),
            ],
            options={
                'db_table': 'valor_calidad',
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(db_column='secuencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('process_code', models.ForeignKey(db_column='proceso_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.process')),
                ('route_code', models.ForeignKey(db_column='ruta_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.route')),
            ],
            options={
                'db_table': 'punto_ruta',
            },
        ),
        migrations.CreateModel(
            name='SelectedPath',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(db_column='secuencia')),
                ('start_real_datetime', models.DateField(blank=True, db_column='fecha_hora_inicio_real', null=True)),
                ('end_real_datetime', models.DateField(blank=True, db_column='fecha_hora_fin_real', null=True)),
                ('start_estimated_datetime', models.DateField(blank=True, db_column='fecha_hora_inicio_estimada', null=True)),
                ('end_estimated_datetime', models.DateField(blank=True, db_column='fecha_hora_fin_estimado', null=True)),
                ('incoming_fabric_quantity', models.IntegerField(blank=True, db_column='cantidad_tela_entrante', null=True)),
                ('outgoing_fabric_quantity', models.IntegerField(blank=True, db_column='cantidad_tela_saliente', null=True)),
                ('unit', models.IntegerField(blank=True, db_column='unidad', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('fabric_batch_code', models.ForeignKey(db_column='partida_tela_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.fabricbatch')),
                ('machinery_process_code', models.ForeignKey(db_column='proceso_maquinaria_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.processmachinery')),
                ('pdf_code', models.ForeignKey(blank=True, db_column='partida_articulo_proceso_pdf_codigo', null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.articleprocesspdf')),
                ('quality_values_code', models.ForeignKey(blank=True, db_column='valor_calidad_codigo', null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.qualityvalues')),
                ('user', models.ForeignKey(blank=True, db_column='usuario_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trayecto_seleccionado',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('code', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('start_datetime', models.DateField(db_column='fecha_hora_inicio')),
                ('estimated_completion_datetime', models.DateField(blank=True, db_column='fecha_hora_estimada_finalizacion', null=True)),
                ('real_completion_datetime', models.DateField(blank=True, db_column='fecha_hora_finalizacion_real', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('machinery_code', models.ForeignKey(db_column='maquinaria_codigo', on_delete=django.db.models.deletion.CASCADE, to='tareo.machinery')),
                ('reason_code', models.ForeignKey(db_column='razon_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.reason')),
            ],
            options={
                'db_table': 'parada',
            },
        ),
        migrations.CreateModel(
            name='ContainerSelectedTrajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('container_code', models.ForeignKey(db_column='contenedor_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.container')),
                ('selected_trajectory_code', models.ForeignKey(db_column='trayecto_seleccionado_codigo', on_delete=django.db.models.deletion.CASCADE, to='kanban.selectedpath')),
            ],
            options={
                'db_table': 'contenedor_trayecto_seleccionado',
                'unique_together': {('selected_trajectory_code', 'container_code')},
            },
        ),
    ]
