# Generated by Django 5.0.1 on 2024-02-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='type_reason',
        ),
        migrations.AddField(
            model_name='stop',
            name='type_reason',
            field=models.IntegerField(choices=[(1, 'Parada no programada'), (2, 'Parada programada'), (3, 'Llamada supervisor')], db_column='estado', default=1),
        ),
        migrations.AlterField(
            model_name='fabricbatch',
            name='destination_type',
            field=models.CharField(blank=True, db_column='tipo_destino', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fabricbatch',
            name='packaging_type',
            field=models.CharField(blank=True, db_column='tipo_embalaje', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fabricbatch',
            name='production_type',
            field=models.CharField(blank=True, db_column='tipo_produccion', max_length=255, null=True),
        ),
    ]
