# Generated by Django 5.0.1 on 2024-02-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricbatch',
            name='state',
            field=models.CharField(choices=[('A', 'Activo'), ('F', 'Finalizada')], db_column='estado', default='A', max_length=1),
        ),
        migrations.AlterModelTable(
            name='processmachinery',
            table='proceso_maquinaria',
        ),
    ]
