# Generated by Django 5.0.1 on 2024-02-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_parameterprocess_parameterstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricbatch',
            name='target_date',
            field=models.DateTimeField(db_column='fecha_objetivo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='delivery_deadline',
            field=models.DateTimeField(db_column='fecha_limite_entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, db_column='fecha_pedido', null=True),
        ),
        migrations.AlterField(
            model_name='selectedpath',
            name='end_estimated_datetime',
            field=models.DateTimeField(blank=True, db_column='fecha_hora_fin_estimado', null=True),
        ),
        migrations.AlterField(
            model_name='selectedpath',
            name='end_real_datetime',
            field=models.DateTimeField(blank=True, db_column='fecha_hora_fin_real', null=True),
        ),
        migrations.AlterField(
            model_name='selectedpath',
            name='start_estimated_datetime',
            field=models.DateTimeField(blank=True, db_column='fecha_hora_inicio_estimada', null=True),
        ),
        migrations.AlterField(
            model_name='selectedpath',
            name='start_real_datetime',
            field=models.DateTimeField(blank=True, db_column='fecha_hora_inicio_real', null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='estimated_completion_datetime',
            field=models.DateTimeField(blank=True, db_column='fecha_hora_estimada_finalizacion', null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='real_completion_datetime',
            field=models.DateTimeField(blank=True, db_column='fecha_hora_finalizacion_real', null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='start_datetime',
            field=models.DateTimeField(db_column='fecha_hora_inicio'),
        ),
    ]
