# Generated by Django 5.0.1 on 2024-02-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_alter_fabricbatch_target_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedpath',
            name='unit',
            field=models.CharField(blank=True, db_column='unidad', max_length=255, null=True),
        ),
    ]
