# Generated by Django 5.0.1 on 2024-02-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_alter_selectedpath_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(blank=True, db_column='fecha_creacion', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_deadline_date',
            field=models.DateTimeField(blank=True, db_column='fecha_limite_entrega', null=True),
        ),
        migrations.AlterModelTable(
            name='container',
            table=None,
        ),
    ]
