# Generated by Django 5.0.1 on 2024-02-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0008_remove_order_order_date_order_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=4, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='descripcion', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'zona',
            },
        ),
        migrations.AlterModelTable(
            name='container',
            table='contenedor',
        ),
        migrations.AddField(
            model_name='container',
            name='zone_code',
            field=models.ForeignKey(blank=True, db_column='zona_codigo', null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.zone'),
        ),
    ]
