# Generated by Django 5.0.1 on 2024-02-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_zone_alter_container_table_container_zone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricroll',
            name='kilograms',
            field=models.FloatField(db_column='kilos'),
        ),
        migrations.AlterField(
            model_name='processmachinery',
            name='cost_dollars_kg',
            field=models.FloatField(blank=True, db_column='costo_dolares_kg', null=True),
        ),
        migrations.AlterField(
            model_name='processmachinery',
            name='cost_dollars_mts',
            field=models.FloatField(blank=True, db_column='costo_dolares_mts', null=True),
        ),
        migrations.AlterField(
            model_name='processmachinery',
            name='speed_kg',
            field=models.FloatField(blank=True, db_column='velocidad_kg', null=True),
        ),
        migrations.AlterField(
            model_name='processmachinery',
            name='speed_mts',
            field=models.FloatField(blank=True, db_column='velocidad_mts', null=True),
        ),
        migrations.AlterField(
            model_name='qualityfield',
            name='evaluable',
            field=models.FloatField(blank=True, db_column='evaluable', null=True),
        ),
        migrations.AlterField(
            model_name='qualityfield',
            name='max_alert',
            field=models.FloatField(blank=True, db_column='maximo_alerta', null=True),
        ),
        migrations.AlterField(
            model_name='qualityfield',
            name='max_approval',
            field=models.FloatField(blank=True, db_column='maximo_aprobacion', null=True),
        ),
        migrations.AlterField(
            model_name='qualityfield',
            name='min_alert',
            field=models.FloatField(blank=True, db_column='minimo_alerta', null=True),
        ),
        migrations.AlterField(
            model_name='qualityfield',
            name='min_approval',
            field=models.FloatField(blank=True, db_column='minimo_aprobacion', null=True),
        ),
        migrations.AlterField(
            model_name='qualityfield',
            name='standard_value',
            field=models.FloatField(blank=True, db_column='valor_estandar', null=True),
        ),
        migrations.AlterField(
            model_name='qualityvalues',
            name='result',
            field=models.FloatField(blank=True, db_column='resultado', null=True),
        ),
        migrations.AlterField(
            model_name='qualityvalues',
            name='value',
            field=models.FloatField(db_column='valor'),
        ),
        migrations.AlterField(
            model_name='selectedpath',
            name='incoming_fabric_quantity',
            field=models.FloatField(blank=True, db_column='cantidad_tela_entrante', null=True),
        ),
        migrations.AlterField(
            model_name='selectedpath',
            name='outgoing_fabric_quantity',
            field=models.FloatField(blank=True, db_column='cantidad_tela_saliente', null=True),
        ),
    ]
