# Generated by Django 5.0.1 on 2024-02-01 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='descripcion', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=8, primary_key=True, serialize=False)),
                ('dni', models.CharField(blank=True, db_column='dni', max_length=255, null=True)),
                ('first_name', models.CharField(db_column='nombre', max_length=255)),
                ('last_name', models.CharField(db_column='apellido', max_length=255)),
                ('phone', models.IntegerField(blank=True, db_column='telefono', null=True)),
                ('address', models.IntegerField(blank=True, db_column='direccion', null=True)),
                ('photo', models.ImageField(blank=True, db_column='foto', null=True, upload_to='images/empleado/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modificacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role_code', models.ForeignKey(db_column='rol_codigo', on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.role')),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
    ]
