# Generated by Django 5.0.1 on 2024-02-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='line',
            field=models.CharField(blank=True, choices=[('A', 'Abierta'), ('T', 'Tubular'), ('H', 'Ambas')], db_column='linea', max_length=1, null=True),
        ),
    ]
